# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aca1446b1dc29ad8b9ec65c7a082edbda224a9a37e9df733b61493327a0e644c9ca92a91a905121457bb017334d3bf97d7abcdca58da344fc0de3296898904d7

test:
  secret_key_base: 28bf095e7ffee595fae7ee59dc862dc3833fd40733b3d7f96268a137ebc3c574e017fe6cd9c34f2cd9e0b20605590c53ecbbddbdddf16ee5ac8e22cc20ef20bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
